### ISSUE TITLE
rule with DateTime fact and generates fact with string causes an error

### ISSUE THREAD

**Issue by mcneilm4** [ulfurinn/wongi-engine#56]
```
engine = Wongi::Engine.create
engine << Wongi::Engine::DSL::rule :active_less_than_1_of_last_7_days do
      for_all {
        has :last_capture_at, :CustomerId, :LastCaptureAt
        any {
          option {
            same :LastCaptureAt, nil
          }
          option {
            assign :SevenDaysAgo do
              Time.current - 7.days
            end
            diff :LastCaptureAt, nil
            less :LastCaptureAt, :SevenDaysAgo
          }
        }
      }
      make {
        gen :decline_reason, :CustomerId, 'active_less_than_1_of_last_7_days'
      }
    end

engine << [:last_cature_at, 'token1', Time.current - 7.days]
```

callstack:

```
/Users/meghanm/.rvm/gems/ruby-2.3.1/gems/activesupport-4.1.15/lib/active_support/core_ext/string/conversions.rb:54:in 'parse': invalid date (ArgumentError)
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/activesupport-4.1.15/lib/active_support/core_ext/string/conversions.rb:54:in 'to_datetime'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/activesupport-4.1.15/lib/active_support/core_ext/date_time/calculations.rb:157:in '<=>'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/activesupport-4.1.15/lib/active_support/core_ext/time/calculations.rb:241:in 'compare_with_coercion'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/activesupport-4.1.15/lib/active_support/time_with_zone.rb:214:in '<=>'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/wme.rb:78:in '=='
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/wme.rb:78:in 'match_member'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/wme.rb:52:in '=~'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/network.rb:334:in 'block in find'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/enumerators.rb:6:in '<<'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/enumerators.rb:6:in 'block (2 levels) in new'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/enumerators.rb:5:in 'each'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/enumerators.rb:5:in 'block in new'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/network.rb:334:in 'each'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/network.rb:334:in 'each'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/network.rb:334:in 'find'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/network.rb:334:in 'find'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/network.rb:127:in 'real_assert'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/data_overlay.rb:86:in 'block in process_cascade'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/data_overlay.rb:82:in 'each'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/data_overlay.rb:82:in 'process_cascade'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/data_overlay.rb:63:in 'assert'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/network.rb:113:in 'assert'
    from /Users/meghanm/.rvm/gems/ruby-2.3.1/gems/wongi-engine-0.2.9/lib/wongi-engine/network.rb:203:in '<<'
    from ./script/wongi-test.rb:137:in 'load_facts'
    from ./script/wongi-test.rb:183:in '<main>'
```

**Comment by ulfurinn** [comment]
Cannot reproduce from what you've posted. Please provide a full self-contained code sample triggering the issue.

**Comment by mcneilm4** [comment]
That's really weird. I uploaded a txt file with my ruby script that repros 100% of the time. 
[isolated_wongi_test.txt](https://github.com/ulfurinn/wongi-engine/files/351103/isolated_wongi_test.txt)
